#!/usr/bin/env python3
"""
Generate C++ build info header from Bazel workspace status files.

This script reads stable-status.txt and volatile-status.txt files produced by
workspace_status_command and generates a C++ source file with build information.

USAGE:
    python generate_build_info.py <stable_status> <volatile_status> <output>
"""

import sys
import os

def read_status_file(path):
    """Read workspace status file and return dict of key-value pairs."""
    values = {}
    if not os.path.exists(path):
        return values
    
    with open(path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            # Format: KEY value (space-separated)
            parts = line.split(' ', 1)
            if len(parts) == 2:
                values[parts[0]] = parts[1]
    return values

def escape_string(s):
    """Escape string for C++ string literal."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')

def generate_cpp_source(stable_values, volatile_values, output_path):
    """Generate C++ source file with build info."""
    
    # Get values with fallbacks
    git_sha = volatile_values.get('BUILD_SCM_REVISION', 'unknown')
    git_branch = stable_values.get('STABLE_GIT_BRANCH') or stable_values.get('BUILD_EMBED_LABEL', 'unknown')
    build_time = volatile_values.get('BUILD_TIMESTAMP', 'unknown')
    git_status = volatile_values.get('BUILD_SCM_STATUS', 'unknown')
    build_user = stable_values.get('BUILD_USER', 'unknown')
    build_host = stable_values.get('BUILD_HOST', 'unknown')
    
    # Escape for C++
    git_sha = escape_string(git_sha)
    git_branch = escape_string(git_branch)
    build_time = escape_string(build_time)
    git_status = escape_string(git_status)
    build_user = escape_string(build_user)
    build_host = escape_string(build_host)
    
    # Generate C++ source
    cpp_source = f'''// GENERATED FILE - DO NOT EDIT
// Generated by generate_build_info.py from workspace status files

#include "Build/Info.h"

const char* Build::Info::GitSha() {{
    return "{git_sha}";
}}

const char* Build::Info::GitBranch() {{
    return "{git_branch}";
}}

const char* Build::Info::BuildTime() {{
    return "{build_time}";
}}

const char* Build::Info::GitStatus() {{
    return "{git_status}";
}}

const char* Build::Info::BuildUser() {{
    return "{build_user}";
}}

const char* Build::Info::BuildHost() {{
    return "{build_host}";
}}
'''
    
    with open(output_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(cpp_source)

def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <stable-status.txt> <volatile-status.txt> <output.cc>", file=sys.stderr)
        sys.exit(1)
    
    stable_path = sys.argv[1]
    volatile_path = sys.argv[2]
    output_path = sys.argv[3]
    
    # Read workspace status files
    stable_values = read_status_file(stable_path)
    volatile_values = read_status_file(volatile_path)
    
    # Generate C++ source
    generate_cpp_source(stable_values, volatile_values, output_path)
    
    print(f"Generated build info: {output_path}")

if __name__ == '__main__':
    main()
